"use client";

type TransactionType = "Income" | "Expense";
type FinanceAccount = { id: string; name: string };
type FinanceCategory = { id: string; name: string; type: "Income" | "Expense" };
type FinanceRecurring = { id: string; type: TransactionType; accountId: string; amount: number; category: string; note: string; dayOfMonth: number; active: boolean; createdAt: string; generatedMonths: string[] };

type Props = {
  selectedMonth: string; onMonthChange: (v:string)=>void; recurring: FinanceRecurring[]; accounts: FinanceAccount[]; incomeCategories: FinanceCategory[]; expenseCategories: FinanceCategory[];
  editingRecurringId: string|null; recurringType: TransactionType; recurringAccountId:string; recurringAmount:string; recurringCategory:string; recurringNote:string; recurringDay:string; recurringError:string;
  onOpenAddRecurring:()=>void; onOpenEditRecurring:(x:FinanceRecurring)=>void; onCloseRecurringEditor:()=>void; onRecurringTypeChange:(v:TransactionType)=>void; onRecurringAccountChange:(v:string)=>void; onRecurringAmountChange:(v:string)=>void; onRecurringCategoryChange:(v:string)=>void; onRecurringNoteChange:(v:string)=>void; onRecurringDayChange:(v:string)=>void; onSaveRecurring:()=>void; onDeleteRecurring:(x:FinanceRecurring)=>void; onToggleRecurring:(x:FinanceRecurring)=>void; onGenerateRecurring:(x:FinanceRecurring)=>void; formatRupiah:(n:number)=>string; formatMonth:(m:string)=>string;
};

export default function FinanceRecurring(p:Props){
  const cats=p.recurringType==="Income"?p.incomeCategories:p.expenseCategories;
  return <section className="mt-7">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-widest opacity-50">Automation</p><h3 className="mt-1 text-xl font-bold">Recurring Transactions</h3><p className="mt-1 max-w-2xl text-sm leading-6 opacity-55">Simpan transaksi rutin sebagai template. Tidak ada transaksi yang dibuat otomatis; generate dilakukan manual untuk bulan yang dipilih.</p></div><button type="button" onClick={p.onOpenAddRecurring} disabled={!p.accounts.length} className="rounded-xl bg-[#8f806d] px-4 py-2.5 text-sm font-medium text-white disabled:opacity-40">+ Add Recurring</button></div>
    <div className="mt-4 rounded-3xl bg-white/60 p-5 shadow-sm flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-widest opacity-40">Generate month</p><p className="mt-1 text-sm opacity-55">Satu template hanya bisa digenerate sekali per bulan.</p></div><input type="month" value={p.selectedMonth} onChange={e=>p.onMonthChange(e.target.value)} className="rounded-xl border border-[#d8cec0] bg-white px-4 py-2.5 text-base"/></div>
    {p.editingRecurringId && <div className="mt-4 rounded-3xl bg-white/70 p-5 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-xs uppercase tracking-widest opacity-40">{p.editingRecurringId === "__new__" ? "New recurring" : "Edit recurring"}</p><h4 className="mt-1 text-lg font-semibold">Recurring template</h4></div><button type="button" onClick={p.onCloseRecurringEditor} className="rounded-lg px-3 py-2 text-sm opacity-60">Close</button></div>
      <div className="mt-4 grid gap-4 md:grid-cols-2">
        <div><label className="text-sm font-medium">Type</label><div className="mt-2 grid grid-cols-2 gap-2">{(["Expense","Income"] as TransactionType[]).map(t=><button key={t} type="button" onClick={()=>p.onRecurringTypeChange(t)} className={`rounded-xl border px-4 py-3 text-sm font-medium ${p.recurringType===t?"border-[#8f806d] bg-[#8f806d] text-white":"border-[#d8cec0] bg-white"}`}>{t}</button>)}</div></div>
        <div><label className="text-sm font-medium">Account</label><select value={p.recurringAccountId} onChange={e=>p.onRecurringAccountChange(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d8cec0] bg-white px-4 py-3 text-base"><option value="">Select account</option>{p.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div>
        <div><label className="text-sm font-medium">Amount</label><input type="number" min="1" value={p.recurringAmount} onChange={e=>p.onRecurringAmountChange(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d8cec0] bg-white px-4 py-3 text-base"/></div>
        <div><label className="text-sm font-medium">Day of month</label><input type="number" min="1" max="31" value={p.recurringDay} onChange={e=>p.onRecurringDayChange(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d8cec0] bg-white px-4 py-3 text-base"/></div>
        <div><label className="text-sm font-medium">Category</label><select value={p.recurringCategory} onChange={e=>p.onRecurringCategoryChange(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d8cec0] bg-white px-4 py-3 text-base"><option value="">Select category</option>{cats.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select></div>
        <div><label className="text-sm font-medium">Note</label><input value={p.recurringNote} onChange={e=>p.onRecurringNoteChange(e.target.value)} className="mt-2 w-full rounded-xl border border-[#d8cec0] bg-white px-4 py-3 text-base" placeholder="Optional"/></div>
      </div>{p.recurringError&&<p className="mt-4 rounded-xl bg-[#f5e4dc] px-4 py-3 text-sm text-[#8b4e3e]">{p.recurringError}</p>}<div className="mt-4 flex gap-2"><button type="button" onClick={p.onSaveRecurring} className="rounded-xl bg-[#8f806d] px-4 py-2.5 text-sm font-medium text-white">Save Recurring</button><button type="button" onClick={p.onCloseRecurringEditor} className="rounded-xl bg-[#ddd4c7] px-4 py-2.5 text-sm font-medium">Cancel</button></div>
    </div>}
    {!p.recurring.length?<div className="mt-4 rounded-3xl bg-white/60 p-8 text-center shadow-sm"><p className="text-3xl">🔁</p><p className="mt-3 font-semibold">No recurring transactions yet.</p><p className="mt-1 text-sm opacity-50">Simpan pemasukan atau pengeluaran rutin di sini.</p></div>:<div className="mt-4 space-y-3">{p.recurring.map(x=>{const generated=x.generatedMonths.includes(p.selectedMonth);const account=p.accounts.find(a=>a.id===x.accountId)?.name??"Unknown account";return <div key={x.id} className="rounded-3xl bg-white/60 p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#eee7dd] px-2.5 py-1 text-xs font-medium">{x.type}</span><span className="text-xs opacity-45">Every month · day {x.dayOfMonth}</span>{!x.active&&<span className="rounded-full bg-[#f0e2db] px-2.5 py-1 text-xs text-[#8b4e3e]">Paused</span>}</div><h4 className="mt-2 text-lg font-semibold">{x.category||"Uncategorized"}</h4><p className="text-sm opacity-55">{account} · {x.note||"No note"}</p></div><div className="text-right"><p className={`text-lg font-bold ${x.type==="Income"?"text-[#52745b]":"text-[#9a6254]"}`}>{x.type==="Income"?"+":"-"}{p.formatRupiah(x.amount)}</p><p className="mt-1 text-xs opacity-45">{generated?`Generated for ${p.formatMonth(p.selectedMonth)}`:`Not generated for ${p.formatMonth(p.selectedMonth)}`}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>p.onGenerateRecurring(x)} disabled={!x.active||generated} className="rounded-xl bg-[#8f806d] px-3 py-2 text-sm font-medium text-white disabled:opacity-40">{generated?"Generated ✓":`Generate ${p.formatMonth(p.selectedMonth)}`}</button><button type="button" onClick={()=>p.onToggleRecurring(x)} className="rounded-xl bg-[#ddd4c7] px-3 py-2 text-sm font-medium">{x.active?"Pause":"Activate"}</button><button type="button" onClick={()=>p.onOpenEditRecurring(x)} className="rounded-xl bg-[#eee7dd] px-3 py-2 text-sm font-medium">Edit</button><button type="button" onClick={()=>p.onDeleteRecurring(x)} className="rounded-xl bg-[#f0e2db] px-3 py-2 text-sm font-medium text-[#8b4e3e]">Delete</button></div></div>})}</div>}
  </section>;
}